//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lovesnwishes.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComment
    {
        public int Id { get; set; }
        public int FeedId { get; set; }
        public string Comment { get; set; }
        public int CommentType { get; set; }
        public bool IsActive { get; set; }
        public int CommentedBy { get; set; }
        public System.DateTime CommentedDate { get; set; }
    }
}
