//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lovesnwishes.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeed
    {
        public int Id { get; set; }
        public Nullable<int> FeedType { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Feed { get; set; }
        public bool IsDeleted { get; set; }
        public string MediaFolder { get; set; }
        public string MediaContent { get; set; }
    }
}
