//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lovesnwishes.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFriendMapping
    {
        public int Id { get; set; }
        public int SendFrom { get; set; }
        public int SendTo { get; set; }
        public bool isFriend { get; set; }
        public System.DateTime SentOn { get; set; }
    }
}
