//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lovesnwishes.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public bool IsActive { get; set; }
        public string ProfileImageUrl { get; set; }
        public string Password { get; set; }
    }
}
